### ISSUE TITLE
Issue with delete node "No id to delete ..."

### ISSUE THREAD

**Issue by skylord123** [julien-pal/node-red-contrib-elasticsearch#1]
Hey, thanks for making a ES client for NR. I'm trying it out but I've ran into issues with the delete node always erroring with a status of "No id to delete ...".

When I checked the code I noticed the statement that triggers this relies on `deleteConfig.esId` being set, but it never gets set. It looks like it is supposed to be `deleteConfig.id`:
https://github.com/julien-pal/node-red-contrib-elasticsearch/blob/036c493612f9f6f4d3d324d991479617899a1081/elasticsearch/elasticsearch-delete.js#L38

**Comment by skylord123** [comment]
I just modified the file within my node_modules folder to use `deleteConfig.id` instead and it is now working as it's supposed to. This will need to be fixed.

**Comment by julien-pal** [comment]
Hi !
Thanks for the heads up. 
I made your correction, it's available in the version 1.1.2 of the npm package.

**Comment by skylord123** [comment]
That was quick, thanks!
