### ISSUE TITLE
Elastic doc "type" param mismatch for bulk node

### ISSUE THREAD

**Issue by abhishek063** [julien-pal/node-red-contrib-elasticsearch#18]
The elasticsearch-bulk.html is expecting "esType" as param, however, the elasticsearch-bulk.js expects and processes the same param as "type". This mismatch causes the "esType" value to get ignored when specified in the node. One needs to explicitly set the "type", before passing on the msg to the elastic-bulk, to get the desired results.

**Comment by julien-pal** [comment]
Hi, 
It's fixed in the new release !

**Comment by abhishek063** [comment]
Thank you for taking care of it promptly.
